# Generated by Django 5.0.1 on 2024-01-24 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
    ]
