GROUPS = ["KI-32", "KN-11", "IS-23"]
SUBJECTS = ["MATH", "UKRAINIAN", "HISTORY", "ENGLISH", "PHILOSOPHY", "PROGRAMMING"]
TEACHERS_COUNT = 5
STUDENTS_COUNT = 50
GRADES_COUNT = 20

CONFIG_FILE = "config.ini"
