"""Release

Revision ID: 15840ab347fd
Revises: 1a68ec0dc935
Create Date: 2024-02-01 14:45:59.389617

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "15840ab347fd"
down_revision: Union[str, None] = "1a68ec0dc935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_todos_title", table_name="todos")
    op.drop_table("todos")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todos",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=250), autoincrement=False, nullable=True
        ),
        sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="todos_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="todos_pkey"),
    )
    op.create_index("ix_todos_title", "todos", ["title"], unique=True)
    # ### end Alembic commands ###
